# This is the configuration file for the RusQTTbom program

[location]
# Got to https://weather.bom.gov.au/location/r3gx2f8-sydney and type in your location.
# When you get a result you are after, note the name below.
# Also copy the hash after the /location/ slug below.
# The hash is normally 7 digits. If this doesn't work, remove the last digit.
# Both location values need to be surrounded in double quotation marks.
name = "Sydney"         # like "Sydney"
hash = "r3gx2f"         # like "r3gx2f8"

[broker]
ip = ""                 # like "192.168.1.55"
port = 1883             # like 1883 which is a common default mqtt broker port

[validation]
# These values are about data validation
# This is the catch erroneous entries like -99 or 999 etc.
# Ensure min and max values are outside what is possible
# These values are likely to be location / climate dependent
# Change the values only, do not change the spelling or wording of the fields
mintemp = -20.0
maxtemp = 50.0
minwind = 0.0
maxwind = 400.0
minhumidity = 0.0
maxhumidity = 100.0
minrain = 0.0
maxrain = 300.0

[topics]
# MQTT topics MUST NOT have a / at the beginning or end of the topic.
# Topics can have any number of levels, for example...
# A valid topic is "test". Another is "test/first". Another is "test/first/second".
# These are invalid: "/test", "test/" and "/test/".
# The following example topics can be changed to fit your MQTT topic naming scheme.
# Do NOT change the fields themselves.
temp = "outside/weather/current-temp"
tempfeels = "outside/weather/temp-feels"
mintemp = "outside/weather/min-temp"
maxtemp = "outside/weather/max-temp"
humidity = "outside/weather/humidity"
rain = "outside/weather/rain-today"
windkms = "outside/weather/wind-kms"
winddir = "outside/weather/wind-dir"
gusts = "outside/weather/gusts-kms"
maxgust = "outside/weather/max-gust"

